#!/usr/bin/env python
"""Compatibility wrapper for the canonical DynUNet trainer entrypoint."""

from __future__ import annotations

from src.models.dynnet_config import (
    DEFAULT_CANCERVISION_DATASET_ROOT,
    DEFAULT_CANCERVISION_TASK_MANIFEST,
    DEFAULT_DATA_DIR,
    DEFAULT_GPU_PROFILE_NAME,
    DEFAULT_NUM_SAMPLES,
    DEFAULT_ROI_SIZE,
    DEFAULT_SAVE_DIR,
    DEFAULT_VAL_SW_BATCH_SIZE,
    GPU_PROFILE_ALIASES,
    GPU_PROFILE_CONFIGS,
    GpuProfileConfig,
    REPO_ROOT,
    WANDB_ENTITY,
    WANDB_PROJECT,
    DatasetConfig,
    build_run_name,
    parse_args,
    validate_args,
)
from src.models.dynnet_data import (
    apply_path_prefix_maps,
    build_cancervision_segmentation_splits,
    build_data_dicts,
    build_dataset_splits,
    infer_cancervision_path_prefix_maps,
    get_brats_train_transforms,
    get_brats_val_transforms,
    get_cancervision_binary_seg_train_transforms,
    get_cancervision_binary_seg_val_transforms,
    get_dataset_config,
    parse_path_prefix_map,
    resolve_cancervision_task_manifest_path,
)
from src.models.dynnet_runtime import (
    RuntimeContext,
    apply_gpu_profile_defaults,
    bootstrap_distributed_env,
    build_micro_batch_slices,
    cleanup_distributed,
    detect_gpu_profile_from_constraints,
    detect_gpu_profile_from_device,
    detect_requested_world_size,
    format_cuda_memory_summary,
    get_autocast_context,
    get_distributed_env,
    get_env_int,
    is_cuda_oom_error,
    is_main_process,
    normalize_gpu_profile_name,
    rank0_print,
    reduce_mean,
    resolve_cuda_device_index,
    resolve_gpu_profile,
    setup_device_and_distributed,
    should_use_amp,
    synchronize,
)
from src.models.dynnet_train import (
    NoOpWandbRun,
    build_model,
    build_model_with_filters,
    load_resume_state,
    main,
    maybe_init_wandb,
    save_last_checkpoint,
    train_one_epoch,
    validate,
)

__all__ = [
    "DEFAULT_CANCERVISION_DATASET_ROOT",
    "DEFAULT_CANCERVISION_TASK_MANIFEST",
    "DEFAULT_DATA_DIR",
    "DEFAULT_GPU_PROFILE_NAME",
    "DEFAULT_NUM_SAMPLES",
    "DEFAULT_ROI_SIZE",
    "DEFAULT_SAVE_DIR",
    "DEFAULT_VAL_SW_BATCH_SIZE",
    "DatasetConfig",
    "GPU_PROFILE_ALIASES",
    "GPU_PROFILE_CONFIGS",
    "GpuProfileConfig",
    "NoOpWandbRun",
    "REPO_ROOT",
    "RuntimeContext",
    "WANDB_ENTITY",
    "WANDB_PROJECT",
    "apply_gpu_profile_defaults",
    "apply_path_prefix_maps",
    "bootstrap_distributed_env",
    "build_cancervision_segmentation_splits",
    "build_data_dicts",
    "build_dataset_splits",
    "build_micro_batch_slices",
    "build_model",
    "build_model_with_filters",
    "build_run_name",
    "cleanup_distributed",
    "detect_gpu_profile_from_constraints",
    "detect_gpu_profile_from_device",
    "detect_requested_world_size",
    "format_cuda_memory_summary",
    "get_autocast_context",
    "get_brats_train_transforms",
    "get_brats_val_transforms",
    "get_cancervision_binary_seg_train_transforms",
    "get_cancervision_binary_seg_val_transforms",
    "get_dataset_config",
    "get_distributed_env",
    "get_env_int",
    "is_cuda_oom_error",
    "is_main_process",
    "infer_cancervision_path_prefix_maps",
    "load_resume_state",
    "main",
    "maybe_init_wandb",
    "normalize_gpu_profile_name",
    "parse_args",
    "parse_path_prefix_map",
    "rank0_print",
    "reduce_mean",
    "resolve_cancervision_task_manifest_path",
    "resolve_cuda_device_index",
    "resolve_gpu_profile",
    "save_last_checkpoint",
    "setup_device_and_distributed",
    "should_use_amp",
    "synchronize",
    "train_one_epoch",
    "validate",
    "validate_args",
]


if __name__ == "__main__":
    main()
